services:
  autoconvert:
    build:
      context: https://[token]@github.com/NielHeesakkers/AutoConvert.git#main
    container_name: autoconvert
    restart: unless-stopped
    privileged: true
    ports:
      - "3742:3742"
    volumes:
      - /Users/server/Docker/Config:/app/config
      - /Users/server/Docker/Logs:/app/logs
      - /Users/server/Docker/Backups:/backup
    environment:
      - DOCKER=true
      - TZ=Europe/Amsterdam
      - NAS_IP=192.168.1.10
      - NAS_USER=[user]
      - NAS_PASS=[pass]
      - NAS_MOVIES_SHARE=/Media/Movies
      - NAS_SERIES_SHARE=/Media/Series
